CREATE DATABASE IF NOT EXISTS appJesuita DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
USE appJesuita;

CREATE TABLE Jesuita(
	idJesuita CHAR(15) NOT NULL PRIMARY KEY ON UPDATE CASCADE,
	Nombre VARCHAR(50) NOT NULL,
	Firma VARCHAR(200) NOT NULL
);

CREATE TABLE Lugar(
	idLugar TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ON UPDATE CASCADE,
	nombre VARCHAR(30) NOT NULL
);

CREATE TABLE Maquina(
    ip CHAR(15) NOT NULL PRIMARY KEY,
    nombreAlumno VARCHAR(50) NULL,
    usuario VARCHAR(20) UNIQUE NOT NULL,
    idJesuita CHAR(15) NULL ON UPDATE CASCADE,
    idLugar TINYINT UNSIGNED NULL ON UPDATE CASCADE,
    tipo CHAR (2) NOT NULL,
    idUsuario SMALLINT NOT NULL,
    password varchar(250) NOT NULL,
    CONSTRAINT CH_tipo CHECK (tipo='a' OR tipo='u'),
    CONSTRAINT FK_MaquinaLugar FOREIGN KEY (idLugar) REFERENCES Lugar(idLugar),
    CONSTRAINT FK_MaquinaJesuita FOREIGN KEY (idJesuita) REFERENCES Jesuita(idJesuita)
);

CREATE TABLE Visita(
	numVisita SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ip CHAR(15) NOT NULL,
	idJesuita CHAR(15) NOT NULL UNIQUE ,
	idLugar TINYINT UNSIGNED NOT NULL UNIQUE,
	fechaHora DATE NOT NULL,
    CONSTRAINT CH_ip CHECK (ip <> idJesuita);
	CONSTRAINT FK_visitaJesuita FOREIGN KEY (idJesuita) REFERENCES Maquina(idJesuita),
	CONSTRAINT FK_visitalugar FOREIGN KEY (idLugar) REFERENCES Maquina(idLugar)
);





